name: Prepare build environment for Teensy

inputs:
  arduino_ide_version:
    type: string
    required: true
  teensyduino_verion:
    type: string
    required: true
  gfx-library-version:
    type: string
    required: true

outputs:
  arduino-folder-path:
    value: ${{ steps.vars.outputs.arduino-folder-path }}

runs:
  using: "composite"
  steps:
    - shell: bash
      name: Update packages
      run: sudo apt-get update
      
    - shell: bash
      name: Configure environment variables
      id: vars
      run: |
        echo "::set-output name=arduino-folder-path::$(echo $HOME/arduino_ide/arduino-${{ inputs.arduino_ide_version }})"

    - shell: bash
      name: verify
      run: |
        echo steps.vars.outputs.arduino-folder-path = ${{ steps.vars.outputs.arduino-folder-path }}
        
    - shell: bash
      name: Install Arduino
      run: |
        wget --quiet https://downloads.arduino.cc/arduino-${{ inputs.arduino_ide_version }}-linux64.tar.xz
        mkdir -p $HOME/arduino_ide
        tar xf arduino-${{ inputs.arduino_ide_version }}-linux64.tar.xz -C $HOME/arduino_ide/

    - shell: bash
      name: Install Teensyduino
      run: |
        sudo apt-get -q -y install libxft2
        wget https://www.pjrc.com/teensy/td_${{ inputs.teensyduino_verion }}/TeensyduinoInstall.linux64
        chmod 755 ./TeensyduinoInstall.linux64
        ./TeensyduinoInstall.linux64 --dir=${{ steps.vars.outputs.arduino-folder-path }}
#        ./TeensyduinoInstall.linux64 --dir=$HOME/arduino_ide/arduino-${{ inputs.arduino_ide_version }}

    - shell: bash
      name: Install libraries
      run: |
        ${{ steps.vars.outputs.arduino-folder-path }}/arduino --install-library "GFX Library for Arduino": ${{ inputs.gfx-library-version }}
