name: Setup Build Environment

description: Make sure Arduino and Teensyduino and any other build tools we require are installed

inputs:
  arduino_ide_version:
    required: true
    type: string
  teensyduino_verion:
    required: true
    type: string
    
runs:
  using: "composite"
  steps:
    - shell: bash
      name: Install Arduino
      run: |
        wget --quiet https://downloads.arduino.cc/arduino-${{ inputs.arduino_ide_version }}-linux64.tar.xz
        mkdir ~/arduino_ide
        tar xf arduino-${{ inputs.arduino_ide_version }}-linux64.tar.xz -C $HOME/arduino_ide/
        
    - shell: bash
      name: Install Teensyduino
      run: |
        sudo apt-get update
        sudo apt-get -q -y install libxft2
        wget https://www.pjrc.com/teensy/td_${{ inputs.teensyduino_verion }}/TeensyduinoInstall.linux64
        chmod 755 ./TeensyduinoInstall.linux64
        ./TeensyduinoInstall.linux64 --dir=$HOME/arduino_ide/arduino-${{ inputs.arduino_ide_version }}
