name: Seeeduino Xiao RP2040 build configuration

description: This action simply provides the data we need to build for the Seeeduino Xiao RP2040 microcontroller

inputs:
  preprocessor-define:
    default: "IDENTITY_M_SEEEDUINO_XAIO_RP2040"
  fqbn:
    description: "Fully qualified board name"
    default: "rp2040:rp2040:seeed_xiao_rp2040"
  board-provider-uri:
    type: string
    default: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
  board-id:
    type: string
    default: rp2040:rp2040@2.5.4
  expected-binary-filename:
    type: string
    default: Device.ino.uf2
  additional-compile-flags:
    type: string
    default: -DARDUINO_RASPBERRY_PI_PICO
  screen-driver:
    required: true
  version:
    type: string
    default: 0.0.1
    
outputs:
  binary-path:
    description: The path to the binary file that was built by this action
    value: ${{ steps.building.outputs.binary-path }}
    
runs:
  using: composite
  steps:
    - name: Building
      id: building
      uses: ./.github/actions/build-arduino
      with:
        preprocessor-define: ${{ inputs.preprocessor-define }}
        fqbn: ${{ inputs.fqbn }}
        screen-driver: ${{ inputs.screen-driver }}
        board-provider-uri: ${{ inputs.board-provider-uri }}
        board-id: ${{ inputs.board-id }}
        additional-compile-flags: ${{ inputs.additional-compile-flags }}
        expected-binary-filename: ${{ inputs.expected-binary-filename }}
        version: ${{ inputs.version }}