name: Example Set Output
on: [push]

jobs:
  example-set-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set an output value
        id: step_one
        run: echo ::set-output name=FOO::BAR
      - name: Display the output value
        run: echo The value of FOO is ${{ steps.step_one.outputs.FOO }}
      - name: Now try again but with an action
        uses: ./.github/workflows/action-set-output