name: Verify Devices
on:
  push:
    paths:
      - 'Device/**'
  workflow_dispatch:

jobs:
  Teensy32:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        screen-driver: ["IDENTITY_S_ILI9341", "IDENTITY_S_ILI9488", "IDENTITY_S_ILI9486"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build Teensy 3.2
        uses: ./.github/actions/teensy32
        with:
          screen-driver: ${{ matrix.screen-driver }}

  Teensy40:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        screen-driver: ["IDENTITY_S_ILI9341", "IDENTITY_S_ILI9488", "IDENTITY_S_ILI9486"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build Teensy 4.0
        uses: ./.github/actions/teensy40
        with:
          screen-driver: ${{ matrix.screen-driver }}

  Xiao2040:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        screen-driver: ["IDENTITY_S_ILI9488"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Seeeduino Xiao RP2040
        uses: ./.github/actions/xiao2040
        with:
          screen-driver: ${{ matrix.screen-driver }}
